config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, notice: 'Flat was successfully destroyed.'
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <%= simple_form_for(@flat) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
    </div>
    <br>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/flats/edit.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="container">
  <div class="row row-cols-3">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="card" style="width: 100%; height: 300px;">
          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= flat.address %></h6>
            <pre class="card-text"><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %>     <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></pre>
            <%= link_to 'More info', flat_path(flat), class: "card-link link-primary" %>
            <%= link_to 'Edit', edit_flat_path(flat), class: "card-link link-warning" %>
            <%= link_to 'Remove', flat, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link link-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<div class="card-body">
  <h5 class="card-title"><%= @flat.name %></h5>
  <h6 class="card-subtitle mb-2 text-muted"><%= @flat.address %></h6>
  <pre class="card-text"><i class="fas fa-user-friends"></i> <%= @flat.number_of_guests %>     <i class="fas fa-euro-sign"></i> <%= @flat.price_per_night %></pre>
  <p class="card-text"><%= @flat.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <div class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Simple Airbnb', flats_path, class: "navbar-brand" %>
        <%= link_to 'Add flat', new_flat_path, class: "btn btn-outline-primary" %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>